### PR TITLE
Feature/twitterlogin

### PR DESCRIPTION
**Pull request by jcfausto**
- Merged the main screen made by Matheus
- Redesigned the login screen. Some social logins are disabled or not fully working due to server or setup restrictions. 
- The introductions are being redesigned too.

### CODE REVIEW

**Comment by leomcabral** [comment]
What are the issues with the server?

**Comment by jcfausto** [comment]
I still can't make the twitter login work when using the server endpoint. The server raises a 500 internal error.

**Comment by leomcabral** [comment]
Please. Send me the request you're sending to the server

**Comment by jcfausto** [comment]
Ok. I will send you via Slack.

**Pull request merged**
